development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production  
  :url: redis://redistogo:13e59885e46d0b2d083af59ba0c4a987@soapfish.redistogo.com:10176
  :host: soapfish.redistogo.com
  :port: 10176
  :password: 13e59885e46d0b2d083af59ba0c4a987
  :inline: true
  :timeout: 1
